fix installation error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,6 +21,14 @@ jobs:
     strategy:
       matrix:
         platform: [ubuntu-latest]
+    env:
+      # The hostname used to communicate with the Redis service container
+      REDIS_HOST: localhost
+      # The default Redis port
+      REDIS_PORT: 6379
+      # some plugins still needs this to run their tests...
+      PERL_USE_UNSAFE_INC: 0
+      DEBIAN_FRONTEND: noninteractive
     runs-on: ${{ matrix.platform }}
 
     # Service containers to run with `container-job`
@@ -47,29 +55,15 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get -y install spamassassin cpanminus redis-tools
-      - name: fix permissions
-        run: sudo chmod o-w /usr/local/bin
       - name: install dependencies from Cpan
         run: |
           cpanm -n Redis Digest::ssdeep
           hash -r
-          cpanm --installdeps --notest .  || echo "warn: errors installing required cpan modules have been ignored"
+          sudo cpanm --installdeps --notest .  || echo "warn: errors installing required cpan modules have been ignored"
       - name: load data into Redis
         run: echo 1 | redis-cli -h localhost -x set 3:kOWGgmTIxeVqIYzqh7j02WRFRbsmBn/LJ:k4RTYe1kqpW9s2nDJ
       - name: update Apache SpamAssassin rules
         run: sudo sa-update
       - name: Regression tests
         run: prove -lv t
-
-    env:
-      # The hostname used to communicate with the Redis service container
-      REDIS_HOST: localhost
-      # The default Redis port
-      REDIS_PORT: 6379
-      # some plugins still needs this to run their tests...
-      PERL_USE_UNSAFE_INC: 0
-      AUTHOR_TESTING: 1
-      AUTOMATED_TESTING: 1
-      RELEASE_TESTING: 1
-      DEBIAN_FRONTEND: noninteractive
 
